-
  branches:
    only:
      - master
      - develop
  configuration: Release
  platform: Any CPU
  install:
    - choco install gitversion.portable -y
  environment:
    nuget_api_key:
      secure: TODO
  before_build:
    - ps: nuget restore src/Transformer.sln
    - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  build:
    project: src/Transformer.sln
    verbosity: minimal
  test: off
  after_build:
    - ps: nuget pack nuget/Transformer.VisualStudio.nuspec -Version (get-item env:GitVersion_NuGetVersion).Value
    - cmd: appveyor PushArtifact "Transformer.VisualStudio.%GitVersion_NuGetVersion%.nupkg"
    #- ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER){ nuget push *.nupkg -ApiKey (get-item env:nuget_api_key).Value -Source https://nuget.org/TODO  }
- 
  branches:
    only:
      - /feature/.*/
  configuration: Release
  platform: Any CPU
  pull_requests:
    do_not_increment_build_number: true
  install:
    - choco install gitversion.portable -y
  environment:
    private_nuget_api_key:
      secure: TODO
  nuget:
    account_feed: true
  before_build:
    - ps: nuget restore
    - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  build:
    project: src/Transformer.sln
    verbosity: minimal
  test: off
  after_build:
    - ps: nuget pack nuget/Transformer.VisualStudio.nuspec -Version (get-item env:GitVersion_InformationalVersion).Value
    - ps: nuget push *.nupkg -ApiKey (get-item env:private_nuget_api_key).Value -Source https://ci.appveyor.com/nuget/TODO/api/v2/package
-
  branches:
    only:
      - /.*/merge/
  configuration: Release
  platform: Any CPU
  pull_requests:
    do_not_increment_build_number: true
  install:
    - choco install gitversion.portable -y
  nuget:
    account_feed: true
  before_build:
    - ps: nuget restore
    - ps: gitversion /l console /output buildserver /updateassemblyinfo /b (get-item env:APPVEYOR_REPO_BRANCH).Value
  build:
    project: src/Transformer.sln
    verbosity: minimal
  test: off